#!/bin/bash

Num1=10
Num2=abhishek

Sum=$((Num1 + Num2))
echo "The sum of $Num1 and $Num2 is: $Sum"

Fruits=("Apple" "Banana" "Cherry")
echo "The fruits in the array are: ${Fruits[@]}"
echo "First fruit: ${Fruits[0]}"
echo "Second fruit: ${Fruits[1]}"
echo "Third fruit: ${Fruits[2]}"
echo " the first fruit is ${Fruits[2]}.. Haha im just misleading you "