#! /bin/bash


USERID=$(id -u)

if [ "$USERID" -ne 0 ]; then
    echo "Please run this script as root or using sudo."
    exit 1
fi

echo "Updating package lists..."
dnf install nginx -y

if [ $? -ne 0 ]; then
    echo "Failed to install nginx. Please check your network connection and package manager settings."
    exit 1
else
    echo "nginx installed successfully."
fi